spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    dynamic:
      primary: master
      datasource:
        master:
          type: com.zaxxer.hikari.HikariDataSource
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.16.20.19:3306/trilight2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
          username: root
          password: root
        tds:
          type: com.zaxxer.hikari.HikariDataSource
          driverClassName: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://172.16.20.19:3306/tds?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8&rewriteBatchedStatements=true
          username: root
          password: root
#        erp:
#          type: com.zaxxer.hikari.HikariDataSource
#          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#          url: jdbc:sqlserver://10.0.3.100:1433;databaseName=JHKJ
#          username: sa
#          password: WHjh123456

      strict: true
  servlet:
    multipart:
      max-file-size: 400MB    # 每个文件的最大大小
      max-request-size: 400MB # 总请求的最大大小
  mvc:
    favicon:
      enabled: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

minio:
  url: 172.16.20.19
  access-key: root
  secret-key: root123456
  bucket-name: tds-2